// GENERATED FILE -- do not edit by hand.
// Regenerate with: node scripts/parse-ebay-template.mjs <template.csv>
// Parsed from ebay-template-instruments.csv + ebay-template-accessories.csv on 2026-08-06.

/** Column header exactly as eBay emits it, including the * required markers. */
export const EBAY_COLUMNS: readonly string[] = [
  "*Action(SiteID=US|Country=US|Currency=USD|Version=1193|CC=UTF-8)",
  "CustomLabel",
  "*Category",
  "StoreCategory",
  "*Title",
  "Subtitle",
  "Relationship",
  "RelationshipDetails",
  "ScheduleTime",
  "*ConditionID",
  "*C:Brand",
  "*C:Type",
  "C:Model",
  "C:Series",
  "C:Number of Frets",
  "C:String Configuration",
  "C:Body Type",
  "C:Handedness",
  "C:Body Color",
  "C:Body Material",
  "C:Model Year",
  "C:Fretboard Material",
  "C:Neck Material",
  "C:Set Includes",
  "C:MPN",
  "C:Country of Origin",
  "C:Size",
  "C:Performance Level",
  "C:California Prop 65 Warning",
  "C:Unit Quantity",
  "C:Unit Type",
  "C:Personalize",
  "C:Personalization Instructions",
  "*C:Amplifier Type",
  "C:Number of Speakers",
  "C:Number of Channels",
  "C:Product Line",
  "C:Suitable For",
  "C:Amplifier Technology",
  "C:Power",
  "C:Venue Type",
  "C:Impedance",
  "PicURL",
  "GalleryType",
  "VideoID",
  "*Description",
  "*Format",
  "*Duration",
  "*StartPrice",
  "BuyItNowPrice",
  "BestOfferEnabled",
  "BestOfferAutoAcceptPrice",
  "MinimumBestOfferPrice",
  "*Quantity",
  "ImmediatePayRequired",
  "*Location",
  "ShippingType",
  "ShippingService-1:Option",
  "ShippingService-1:Cost",
  "ShippingService-2:Option",
  "ShippingService-2:Cost",
  "*DispatchTimeMax",
  "PromotionalShippingDiscount",
  "ShippingDiscountProfileID",
  "*ReturnsAcceptedOption",
  "ReturnsWithinOption",
  "RefundOption",
  "ShippingCostPaidByOption",
  "AdditionalDetails",
  "TakeBackPolicyID",
  "Regional TakeBackPolicies",
  "EcoParticipationFee",
  "Product Safety Pictograms",
  "Product Safety Statements",
  "Product Safety Component",
  "Regulatory Document Ids",
  "Manufacturer Name",
  "Manufacturer AddressLine1",
  "Manufacturer AddressLine2",
  "Manufacturer City",
  "Manufacturer Country",
  "Manufacturer PostalCode",
  "Manufacturer StateOrProvince",
  "Manufacturer Phone",
  "Manufacturer Email",
  "Manufacturer ContactURL",
  "Responsible Person 1",
  "Responsible Person 1 Type",
  "Responsible Person 1 AddressLine1",
  "Responsible Person 1 AddressLine2",
  "Responsible Person 1 City",
  "Responsible Person 1 Country",
  "Responsible Person 1 PostalCode",
  "Responsible Person 1 StateOrProvince",
  "Responsible Person 1 Phone",
  "Responsible Person 1 Email",
  "Responsible Person 1 ContactURL",
  "C:Color",
  "C:To Fit",
  "C:Material",
  "C:Position",
  "C:Active/Passive",
  "C:Capacity",
];

export interface CategoryAspects {
  id: string;
  /** Aspects eBay rejects the listing without. */
  required: readonly string[];
  /** Accepted values per aspect, where eBay publishes a closed list. */
  values: Readonly<Record<string, readonly string[]>>;
}

export const CATEGORY_ASPECTS: Readonly<Record<string, CategoryAspects>> = {
  "4713": {
    id: "4713",
    required: ["Brand", "Type"],
    values: {
      "Type": ["Acoustic Bass Guitar", "Acoustic-Electric Bass Guitar", "Electric Bass Guitar"],
      "String Configuration": ["4 String", "5 String", "6 String", "7 String", "8 String", "9 String", "10 String", "12 String"],
      "Body Type": ["Children's", "Double Neck", "Dreadnought", "Fretless", "Grand Auditorium", "Headless", "Hollow", "Jumbo", "Semi-Hollow", "Short Scale", "Solid"],
      "Body Color": ["Beige", "Black", "Blue", "Brown", "Clear", "Gold", "Gray", "Green", "Multicolor", "Orange", "Pink", "Purple", "Red", "Silver", "White", "Yellow"],
      "Handedness": ["Left-Handed", "Right-Handed"],
    },
  },
  "22670": {
    id: "22670",
    required: ["Brand", "Type"],
    values: {
      "Type": ["Humbucker Pickup", "Lipstick Pickup", "Microphone Pickup", "Mini-Humbucker Pickup", "Piezo Pickup", "Preamp Pickup", "Single Coil Pickup", "Soapbar Pickup", "Soundhole Pickup"],
    },
  },
  "22966": {
    id: "22966",
    required: ["Brand"],
    values: {
      "Type": ["Acoustic-Electric Guitar"],
      "String Configuration": ["4 String", "5 String", "6 String", "7 String", "8 String", "9 String", "10 String", "12 String"],
      "Body Color": ["Beige", "Black", "Blue", "Brown", "Clear", "Gold", "Gray", "Green", "Multicolor", "Orange", "Pink", "Purple", "Red", "Silver", "White", "Yellow"],
      "Body Type": ["Children's", "Double Neck", "Dreadnought", "Fretless", "Grand Auditorium", "Hollow", "Jumbo", "Semi-Hollow", "Silent", "Solid"],
      "Handedness": ["Left-Handed", "Right-Handed"],
    },
  },
  "33021": {
    id: "33021",
    required: ["Brand"],
    values: {
      "Type": ["Acoustic Guitar"],
      "String Configuration": ["4 String", "5 String", "6 String", "7 String", "8 String", "9 String", "10 String", "12 String"],
      "Body Type": ["Children's", "Double Neck", "Dreadnought", "Fretless", "Grand Auditorium", "Jumbo", "Mini Jumbo", "Parlor"],
      "Handedness": ["Left-Handed", "Right-Handed"],
      "Body Color": ["Beige", "Black", "Blue", "Brown", "Clear", "Gold", "Gray", "Green", "Multicolor", "Orange", "Pink", "Purple", "Red", "Silver", "White", "Yellow"],
    },
  },
  "33034": {
    id: "33034",
    required: ["Brand"],
    values: {
      "Type": ["Electric Guitar"],
      "Body Color": ["Beige", "Black", "Blue", "Brown", "Clear", "Gold", "Gray", "Green", "Multicolor", "Orange", "Pink", "Purple", "Red", "Silver", "White", "Yellow"],
      "Body Type": ["Baritone", "Children's", "Double Neck", "Fretless", "Headless", "Hollow", "Jazz", "Semi-Hollow", "Silent", "Solid"],
      "String Configuration": ["4 String", "5 String", "6 String", "7 String", "8 String", "9 String", "10 String", "12 String"],
      "Handedness": ["Left-Handed", "Right-Handed"],
    },
  },
  "38072": {
    id: "38072",
    required: ["Brand", "Amplifier Type"],
    values: {
      "Amplifier Type": ["Cabinet", "Combo", "Head", "Stack"],
      "Number of Speakers": ["1", "2", "3", "4", "5", "6", "8"],
      "Amplifier Technology": ["Hybrid", "Modeling", "Solid State", "Vacuum Tube"],
    },
  },
  "41407": {
    id: "41407",
    required: ["Brand"],
    values: {
      "Type": ["Bridge"],
    },
  },
  "41408": {
    id: "41408",
    required: ["Brand", "Type"],
    values: {
      "Type": ["Cover", "Gig Bag", "Hard Case"],
    },
  },
  "41434": {
    id: "41434",
    required: ["Brand"],
    values: {
      "Type": ["Tuning Peg"],
    },
  },
  "46678": {
    id: "46678",
    required: ["Brand", "Type"],
    values: {
      "Type": ["Bindings & Trim", "Ferrule", "Fret Wire", "String Tree", "Tailpiece"],
    },
  },
};

/** Brand names as eBay spells them. Brand is required in every category. */
export const EBAY_BRANDS: readonly string[] = [
  "Unbranded",
  "Access",
  "Accu-Case",
  "Ace Style",
  "Acme",
  "Adagio",
  "Adam Hall",
  "Adastra",
  "ADDA",
  "Adler",
  "Agenda",
  "Aileen",
  "Ajax",
  "Akai",
  "AKG",
  "AKG Acoustics",
  "Alesis",
  "Alexander",
  "Alexander Reeds",
  "Alice",
  "Allen",
  "Allen & Heath",
  "Allora",
  "Aloha",
  "Altieri",
  "Alto",
  "Altus",
  "Alulu",
  "Alvarez",
  "Amati",
  "Ambassador",
  "American Audio",
  "American DJ",
  "Amigo",
  "Ampeg",
  "Amptown Cases",
  "AMS Neve",
  "AMT Electronics",
  "Analog Man",
  "Anatolian",
  "Andreas Eastman",
  "ANTARES",
  "Anton Breton",
  "aNueNue",
  "Anvil",
  "APC",
  "Ape Case",
  "Apex",
  "Aphex",
  "API Audio",
  "Applause",
  "Applecreek",
  "Aquila",
  "Arca-Swiss",
  "Archer",
  "Archos",
  "Arcos Brasil",
  "Aria",
  "Arion",
  "Armstrong",
  "Arriba!",
  "Art",
  "Artisan",
  "Artist",
  "Artley",
  "Arturia",
  "Ashbury",
  "Ashdown",
  "Ashton",
  "Ashville",
  "Aubert",
  "Audio Dynamics",
  "Audion",
  "AudioSpares",
  "Audio Tech",
  "Audix",
  "Augustine",
  "Aulos",
  "Auna",
  "Auris",
  "Austin",
  "Avalon",
  "Avid",
  "Ayotte",
  "AZUMI",
  "B.C. Rich",
  "B&S",
  "Bach",
  "Bacon & Day",
  "Bad Cat",
  "Bagpipes Of Caledonia",
  "Bajaao",
  "BALDWIN",
  "Bam",
  "BAM FRANCE",
  "Banjira",
  "Barber Electronics",
  "Bartolini",
  "Basix",
  "BBE",
  "BBE Sound",
  "BeanBlossom",
  "Beato",
  "Bechstein",
  "Becker",
  "Behringer",
  "Bellafina",
  "Benge",
  "BerkeleyWind",
  "Besson",
  "Best Choice Products",
  "beyerdynamic",
  "Biema",
  "Big Bends",
  "Bigsby",
  "Bishopsound",
  "Bixonic",
  "Black Diamond",
  "Blackstar",
  "Black Swamp Percussion",
  "Blackwood",
  "Blade",
  "Blessing",
  "Blue",
  "Blueridge",
  "Bobelock",
  "Böhm",
  "Bontempi",
  "Boosey & Co",
  "Borg",
  "Bose",
  "Boss",
  "Boston",
  "Bozak",
  "Breedlove",
  "Bridge",
  "Bruce Wei",
  "Bruno",
  "Brunswick",
  "Budda",
  "Buescher",
  "Buffet",
  "Buffet Crampon",
  "Bundy",
  "Bushman",
  "C.A. SEYDEL SÖHNE",
  "C.G. Conn",
  "Cabart",
  "Cahaya",
  "Cakewalk",
  "Cambridge",
  "CAMCO",
  "Cannonball",
  "Carl Fischer",
  "Carl Martin",
  "Carlo Robelli",
  "Carol",
  "Carvin",
  "Casio",
  "Catalinbread",
  "Cecilio",
  "Celestion",
  "Chandler Limited",
  "Charvel",
  "Chauvet",
  "Cherub",
  "Chicago Iron",
  "Chord",
  "Chromaharp",
  "Cibaili",
  "Citronic",
  "Clarity",
  "Clarke",
  "Classic Cantabile",
  "Clayton",
  "Cleartone",
  "ClearWater",
  "CMATMODS",
  "CodaBow",
  "Coemar",
  "Coffin Case",
  "Cole Clark",
  "Collings",
  "Concertone",
  "Conn",
  "Conqueror",
  "Cooperstand",
  "Copley",
  "Corbin",
  "Cordoba",
  "CORE",
  "Cort",
  "Cortex",
  "Cosmic-Audio",
  "Countryman",
  "Courtois",
  "COX",
  "Crate",
  "Creation Audio Labs",
  "Creative",
  "Cremona",
  "Crescent",
  "Crestwood",
  "Crossrock",
  "Crown",
  "Crowther Audio",
  "Crystalcello",
  "Cubase",
  "Cusak",
  "Cymbag",
  "D'Addario",
  "D'Luca",
  "D&A",
  "DAMPIT",
  "Dan Armstrong",
  "Danelectro",
  "Daniel Mari",
  "DAP Audio",
  "Daphon",
  "DARCO",
  "Dava",
  "dbx",
  "ddrum",
  "Dean",
  "Dean Guitars",
  "Dean Markley",
  "DeArmond",
  "Decksaver",
  "DeeJay LED",
  "Deering",
  "DEG",
  "Delrin",
  "DELTALAB",
  "Deluxe",
  "Demo W.Nirshcl",
  "Denis Wick",
  "Denon",
  "Devi Ever",
  "Diamond",
  "Diaz",
  "Dickies",
  "Diesel",
  "Diezel",
  "Digidesign",
  "DigiTech",
  "DiMarzio",
  "Dimavery",
  "Dixie Electric",
  "DMX",
  "Dobro",
  "DOD",
  "DOEPFER",
  "Dolmetsch",
  "Dolnet",
  "Drawmer",
  "Duesenberg",
  "Dunbar",
  "Dunlop",
  "Durastage",
  "Durham Electronics",
  "DW",
  "Dwarfcraft",
  "Dynacord",
  "DYNASTY",
  "E.f Durand",
  "E.M. Winston",
  "E. Rousseau",
  "Earlham",
  "Earl Williams",
  "Eastman",
  "Eastman Winds",
  "Ebony",
  "EBS",
  "Ebtech",
  "Eddy Finn",
  "Edwards",
  "EKHO",
  "Elation",
  "Electro-Harmonix",
  "Electrovision",
  "Electro-Voice",
  "Elite Core",
  "Elixir",
  "ELKHART",
  "elysia",
  "eMedia",
  "Emerson",
  "EMG",
  "Eminence",
  "Emma",
  "Empire",
  "Empirical Labs",
  "E-MU",
  "Engelhardt",
  "Ensoniq",
  "Epiphone",
  "Equinox",
  "Ernie Ball",
  "ESP",
  "Estey",
  "Etude House",
  "Eurolite",
  "Evans",
  "Eventide",
  "Evette",
  "EVH",
  "F. E. Olds",
  "F. Schmidt",
  "Farfisa",
  "Favilla",
  "FEADÓG",
  "Fender",
  "Fenix",
  "Fernandes",
  "FIBRACELL",
  "Fiddlerman",
  "First Act",
  "Fishman",
  "FLEOR",
  "Flinthill",
  "Floyd Rose",
  "Focusrite",
  "Forestone",
  "Fostex",
  "Fox",
  "Fox Bassoons",
  "Foxrox",
  "Framptone",
  "Framus",
  "Frantone",
  "Frederick",
  "Frederick Hemke",
  "Fred Kelly",
  "Freedom Unlimited",
  "Fulltone",
  "Fusion",
  "FZONE",
  "G. Henle Verlag",
  "G.M. Bundy",
  "G&L",
  "Gallien-Krueger",
  "Gard",
  "Gator",
  "Gemeinhardt",
  "Gemini",
  "General Music",
  "Gerhard Baier",
  "Getzen",
  "GEWA",
  "GHS",
  "Giannini",
  "Giardinelli",
  "Gibraltar",
  "Gibson",
  "gig-fx",
  "GigSkinz",
  "Gill Athletics",
  "Glaesel",
  "Gliga",
  "Global",
  "GLS Audio",
  "GMI",
  "Godin",
  "Golden Age Project",
  "Goldstar",
  "Gold Tone",
  "Gonzalez",
  "Gorilla",
  "GOTOH",
  "Goya",
  "Grafix",
  "Grand Concert Select",
  "Graph Tech",
  "Greco",
  "Gretsch",
  "Grey Pneumatic",
  "Griffin",
  "Grover Allman",
  "Grover Products",
  "Gruv Gear",
  "GT Radial",
  "Guardian",
  "Guild",
  "Guyatone",
  "Hagstrom",
  "Hall Crystal Flutes",
  "Hallelu",
  "Hamer",
  "Hamilton",
  "Hammond",
  "Hanika",
  "Hao",
  "HARDCASE",
  "Harley Benton",
  "Harmony",
  "Harrelson",
  "Hartke",
  "Hatfield",
  "Haynes",
  "HD Pro",
  "Heil Sound",
  "Heimer",
  "Helicon",
  "HELMKE",
  "Henri Selmer",
  "Henry Heller",
  "Herco",
  "Hercules",
  "Herdim",
  "Hermida",
  "High End Systems",
  "Hipshot",
  "Höfner",
  "HOHNER",
  "Holton",
  "Hopf",
  "HORA",
  "Hot Picks",
  "Howarth",
  "Hoyer",
  "Huber",
  "Hughes & Kettner",
  "Humes and Berg",
  "Ibanez",
  "Ibiza",
  "IK Multimedia",
  "IMG Stage Line",
  "Indiana",
  "Indigo",
  "Innovative Percussion",
  "IntellaBeam",
  "Intelli",
  "IntelliTouch",
  "Intimidation",
  "IOLITE",
  "ION",
  "IsoAcoustics",
  "ISP",
  "Istanbul",
  "J.W. Pepper",
  "J.W. York & Sons",
  "J.Winter",
  "Jackson",
  "Jackson/Charvel",
  "Jacques",
  "Jahn",
  "Jay Turser",
  "JBL",
  "JB Player",
  "Jean Baptiste",
  "Jetter Gear",
  "JHS",
  "Jim Dunlop",
  "JK",
  "Jodi Head",
  "Joemeek",
  "Johannes Adler",
  "John Pearse",
  "Johnson",
  "Johnson Musical Instruments",
  "JonPaul",
  "JOYO",
  "Jubel Tone",
  "Jupiter",
  "JVC",
  "K&K",
  "K & M",
  "Kaces",
  "Kahler",
  "Kahuna",
  "Kala",
  "Kamaka",
  "KamKase",
  "Kansas",
  "Kanstul",
  "Karl Willhelm",
  "Kawai",
  "Kay",
  "Keeley",
  "Keilwerth",
  "KEIPER",
  "Kent",
  "Ketron",
  "Khaler",
  "Kilberry",
  "Kimball",
  "King",
  "Kingsley",
  "Kingston",
  "Kinman",
  "Klira",
  "Kluson",
  "KMD",
  "Knilling",
  "Koch Industries",
  "Kohala",
  "Kohlert",
  "Kona",
  "KOOL SOUND",
  "Korg",
  "kramer",
  "Kruspe",
  "Kühnl & Hoyer",
  "Kumalae",
  "Kurzweil",
  "KYSER",
  "L.R. Baggs",
  "La Bella",
  "Lakewood",
  "Lakota Leathers",
  "Landgraff",
  "Landstrom's",
  "Laney",
  "Langstile",
  "LANIKAI",
  "Larilee",
  "Lark",
  "Latch Lake",
  "Latin Percussion",
  "Laurèl",
  "Lauren",
  "LD Systems",
  "Le Blanc",
  "Légère Reeds",
  "Lehle",
  "Leolani",
  "Leo Quan",
  "Leprecon",
  "Levy’s",
  "Lexicon",
  "Lida",
  "Line 6",
  "Linof",
  "Live Line",
  "LJ Hutchen",
  "LMI",
  "Lollar Pickups",
  "Lovepedal",
  "Lowrey",
  "LP",
  "Ludwig",
  "Lulu",
  "LUNA",
  "Lyon",
  "Lyon & Healy",
  "Lyons",
  "Mackie",
  "Mad Professor",
  "Maestro",
  "Magma",
  "Magnus",
  "MAHALO",
  "Maharaja Musicals",
  "Malani",
  "Malekko",
  "Mamiya",
  "Manacor",
  "Manhasset",
  "Mapex",
  "Marathon",
  "Marcinkiewicz",
  "Marquez",
  "Marshall",
  "Martin",
  "Matrix",
  "M-Audio",
  "Maxam",
  "Maxon",
  "MAXTONE",
  "Maybell",
  "Mbox",
  "McCallum",
  "MEINL",
  "Meister Walter Nirschl",
  "Mellotron",
  "Memorex",
  "Menatone",
  "Merano",
  "Mesa Boogie",
  "Meyer",
  "MI Audio",
  "MIDAS",
  "Middle Atlantic Products",
  "Mike Ramsey",
  "Mirage",
  "Miraphone",
  "Mitchell",
  "Mixman",
  "Miyazawa",
  "ModTone",
  "Moeck",
  "Mollenhauer",
  "Monette",
  "Monique",
  "Monke",
  "MONO",
  "Montana",
  "MOOG",
  "Morgan Monroe",
  "Morley",
  "Morpheus",
  "MOTU",
  "Muco",
  "Muramatsu",
  "Musafia",
  "Musedo",
  "Musician's Gear",
  "Music Man",
  "Music Man / OLP",
  "MXR",
  "Nady",
  "Native Instruments",
  "Nechville",
  "NEO",
  "Neotech",
  "Neumann",
  "Neutrik",
  "Nirschl",
  "NJD",
  "Nobels",
  "No Bull Music Gear",
  "Nomad",
  "NORD",
  "Nordell",
  "Novation",
  "NSI",
  "Numark",
  "Odyssey",
  "Ohana",
  "Olds",
  "Olds & Sons",
  "Omnitronic",
  "On-Stage",
  "On-Stage Stands",
  "Option 5",
  "Orange",
  "Orion",
  "Orpheum",
  "Ortofon",
  "Oscar Schmidt",
  "OSP",
  "Otto Link",
  "Ovation",
  "Ozark",
  "P. Mauriat",
  "Paiste",
  "Palatino",
  "Paramount",
  "Patricola",
  "Paxman",
  "pBone",
  "PCDJ",
  "Pearl",
  "Peavey",
  "Pedaltrain",
  "Pedalworx",
  "Peli",
  "Pelican",
  "Penn-Elcom",
  "Peripole",
  "Pete Cornish",
  "Peterson Manufacturing",
  "Pettigrew",
  "Phonic",
  "Pignose",
  "Pigtronix",
  "Pioneer",
  "Pioneer DJ",
  "Pirastro",
  "Planet Waves",
  "Plano Model Products",
  "Play-Rite",
  "Plush",
  "Podium Pro",
  "Pono",
  "Ponzol",
  "Porta-Brace",
  "Powell",
  "Premier",
  "ProCo",
  "Pro Co Sound",
  "Proel",
  "Profile",
  "Prolight",
  "Pro-Line Racing",
  "ProMark",
  "Propik",
  "Pro-Tec",
  "Protechtor Cases",
  "Protection Racket",
  "Pro-Tek",
  "Pro X",
  "PRS",
  "Pulse",
  "Pyle",
  "QSC",
  "QTX",
  "QTX Light",
  "QTX Sound",
  "QuickLok",
  "Qwik Tune",
  "Radial",
  "Rajratan",
  "Rally",
  "Rane",
  "RapcoHorizon",
  "Rath",
  "Ravel",
  "Raxxess",
  "RCF",
  "Rebel",
  "Recording King",
  "Red Witch",
  "Rees Harps",
  "Regal",
  "Reloop",
  "Remo",
  "Ren Wei Shi",
  "Reunion Blues",
  "Revere",
  "Reverend",
  "Reynolds",
  "Rhino",
  "Rhodes",
  "Rhythm Band",
  "RIC",
  "Richelieu",
  "Rickenbacker",
  "Rico",
  "Rigotti",
  "Rio",
  "Rio Grande",
  "Ritter",
  "Rivera",
  "RME",
  "RMV",
  "Road Ready",
  "Road Runner",
  "Rockinger",
  "Rocktron",
  "Rockville",
  "Rocky Mountain",
  "Rode",
  "Rodgers",
  "Roger Mayer",
  "Rogers",
  "Rogue",
  "Roland",
  "Roosebeck",
  "Rosetti",
  "Rosewood",
  "Rossetti",
  "Rotosound",
  "Rover (ricambio originale)",
  "Rovner",
  "Royal Stewart",
  "Roy Benson",
  "RS Berkeley",
  "Rythmodik",
  "Sabian",
  "Sabine",
  "Sadowsky",
  "Saga",
  "Salvi",
  "Samick",
  "Samson",
  "Samson Technologies",
  "Sankyo",
  "Savannah",
  "Savoy",
  "Schaller",
  "Schecter",
  "Scherzer",
  "Schilke",
  "Schill",
  "Schiller",
  "Schimmel",
  "Schlagwerk",
  "Schoenhut",
  "SCHOTT",
  "Schreiber",
  "Seiko",
  "Seismic Audio",
  "Selby",
  "Selman",
  "Selmer",
  "Sennheiser",
  "Serato",
  "Session Pro",
  "Seymour Duncan",
  "Sfarzo",
  "Shadow",
  "Shires",
  "Showtec",
  "Shubb",
  "Shure",
  "SIB",
  "Silver Creek",
  "Silverstein Works",
  "Silvertone",
  "Simba",
  "Simmons",
  "SKB",
  "Skreddy Pedals",
  "Skylark",
  "Skytec",
  "Skytronic",
  "SLAPPA",
  "Slingerland",
  "Snarling Dogs",
  "sobbat",
  "Socapex",
  "SOLBRON",
  "Soldano",
  "SOLTON",
  "SONOR",
  "Sony",
  "Soprano",
  "Sound Devices",
  "Soundking",
  "Sound Lab",
  "Sound Percussion Labs",
  "Sovereign",
  "Sovereignent",
  "Spectrum",
  "Sperzel",
  "SPL",
  "Squier",
  "SSL",
  "SS Stewart",
  "Stageline",
  "Stagg",
  "Stanton",
  "Steinberger",
  "Steinway & Sons",
  "Stelling",
  "Stentor",
  "STEVENS",
  "Stomvi",
  "Stork",
  "String Swing",
  "Strunal Schönbach",
  "Subdecay",
  "Suhr",
  "Summit",
  "Superdrum",
  "Suzuki",
  "Swan",
  "Swan Flight",
  "Switchcraft",
  "SWR",
  "Takamine",
  "TAMA",
  "Tamburo",
  "Tanglewood",
  "TASCAM",
  "Taylor",
  "TC Electronic",
  "tech21",
  "Technics",
  "Technobeam",
  "Teisco",
  "TELEFUNKEN",
  "Tempo",
  "THD",
  "The Music Group",
  "The Music Maker",
  "Theo Wanne",
  "The String Centre",
  "the t.racks",
  "Thomann",
  "Thomas",
  "Thomastik-Infeld",
  "Thon",
  "TKL",
  "TOA",
  "ToadWorks",
  "Toca",
  "Tokai",
  "Tonareli",
  "Tone Factor",
  "TonePros",
  "Tonk Bros.",
  "Total Impact",
  "Tov Manufacturing",
  "Tradition Guitars",
  "Trevor James",
  "Trex",
  "Trinity River",
  "Tristar",
  "Trophy",
  "TUDOR",
  "Tyler Mountain",
  "UDG",
  "UFIP",
  "Ultimate Support",
  "Universal",
  "Universal Percussion",
  "Univox",
  "Urei",
  "uxcell",
  "Van Damme",
  "Vandoren",
  "VEGA",
  "VENTURA",
  "Venus",
  "Verne",
  "Vespro",
  "Vestax",
  "VESTER",
  "Vic Firth",
  "Victory Elite",
  "Vincent Bach",
  "Viscount",
  "Visual Sound",
  "Vito",
  "Vocalstyle",
  "VocoPro",
  "Voodoo Lab",
  "Vox",
  "Waldorf",
  "Warburton",
  "Ward & Winterbourn",
  "Warmoth",
  "Warwick",
  "Washburn",
  "Waverly",
  "Way Huge Electronics",
  "Weber",
  "Wedgie",
  "Weltmeister",
  "WENDELL HALL",
  "Weril",
  "Wersi",
  "Westfield",
  "Westone",
  "Wexler",
  "Weymann",
  "Wharfedale",
  "Whirlwind",
  "Wildwood",
  "Wilkinson",
  "Wizard",
  "Woodwind",
  "Wurlitzer",
  "Wurzbach",
  "Xilica Audio Design",
  "Yamaha",
  "Yanagisawa",
  "Yinfente",
  "YORK",
  "Zebra",
  "Zeck",
  "Zildjian",
  "Zither Heaven",
  "Zomo",
  "Zonda",
  "ZOOKIE",
  "Zoom",
];
