// GENERATED FILE -- do not edit by hand.
// Regenerate with: node scripts/parse-ebay-template.mjs <template.csv>
// Parsed from ebay-category-template.csv on 2026-08-06.

/** Column header exactly as eBay emits it, including the * required markers. */
export const EBAY_COLUMNS: readonly string[] = [
  "*Action(SiteID=US|Country=US|Currency=USD|Version=1193|CC=UTF-8)",
  "CustomLabel",
  "*Category",
  "StoreCategory",
  "*Title",
  "Subtitle",
  "Relationship",
  "RelationshipDetails",
  "ScheduleTime",
  "*ConditionID",
  "*C:Brand",
  "*C:Type",
  "C:Model",
  "C:Series",
  "C:Number of Frets",
  "C:String Configuration",
  "C:Body Type",
  "C:Handedness",
  "C:Body Color",
  "C:Body Material",
  "C:Model Year",
  "C:Fretboard Material",
  "C:Neck Material",
  "C:Set Includes",
  "C:MPN",
  "C:Country of Origin",
  "C:Size",
  "C:Performance Level",
  "C:California Prop 65 Warning",
  "C:Unit Quantity",
  "C:Unit Type",
  "C:Personalize",
  "C:Personalization Instructions",
  "*C:Amplifier Type",
  "C:Number of Speakers",
  "C:Number of Channels",
  "C:Product Line",
  "C:Suitable For",
  "C:Amplifier Technology",
  "C:Power",
  "C:Venue Type",
  "C:Impedance",
  "PicURL",
  "GalleryType",
  "VideoID",
  "*Description",
  "*Format",
  "*Duration",
  "*StartPrice",
  "BuyItNowPrice",
  "BestOfferEnabled",
  "BestOfferAutoAcceptPrice",
  "MinimumBestOfferPrice",
  "*Quantity",
  "ImmediatePayRequired",
  "*Location",
  "ShippingType",
  "ShippingService-1:Option",
  "ShippingService-1:Cost",
  "ShippingService-2:Option",
  "ShippingService-2:Cost",
  "*DispatchTimeMax",
  "PromotionalShippingDiscount",
  "ShippingDiscountProfileID",
  "*ReturnsAcceptedOption",
  "ReturnsWithinOption",
  "RefundOption",
  "ShippingCostPaidByOption",
  "AdditionalDetails",
  "TakeBackPolicyID",
  "Regional TakeBackPolicies",
  "EcoParticipationFee",
  "Product Safety Pictograms",
  "Product Safety Statements",
  "Product Safety Component",
  "Regulatory Document Ids",
  "Manufacturer Name",
  "Manufacturer AddressLine1",
  "Manufacturer AddressLine2",
  "Manufacturer City",
  "Manufacturer Country",
  "Manufacturer PostalCode",
  "Manufacturer StateOrProvince",
  "Manufacturer Phone",
  "Manufacturer Email",
  "Manufacturer ContactURL",
  "Responsible Person 1",
  "Responsible Person 1 Type",
  "Responsible Person 1 AddressLine1",
  "Responsible Person 1 AddressLine2",
  "Responsible Person 1 City",
  "Responsible Person 1 Country",
  "Responsible Person 1 PostalCode",
  "Responsible Person 1 StateOrProvince",
  "Responsible Person 1 Phone",
  "Responsible Person 1 Email",
  "Responsible Person 1 ContactURL",
];

export interface CategoryAspects {
  id: string;
  /** Aspects eBay rejects the listing without. */
  required: readonly string[];
  /** Accepted values per aspect, where eBay publishes a closed list. */
  values: Readonly<Record<string, readonly string[]>>;
}

export const CATEGORY_ASPECTS: Readonly<Record<string, CategoryAspects>> = {
  "4713": {
    id: "4713",
    required: ["Brand", "Type"],
    values: {
      "Type": ["Acoustic Bass Guitar", "Acoustic-Electric Bass Guitar", "Electric Bass Guitar"],
      "String Configuration": ["4 String", "5 String", "6 String", "7 String", "8 String", "9 String", "10 String", "12 String"],
      "Body Type": ["Children's", "Double Neck", "Dreadnought", "Fretless", "Grand Auditorium", "Headless", "Hollow", "Jumbo", "Semi-Hollow", "Short Scale", "Solid"],
      "Body Color": ["Beige", "Black", "Blue", "Brown", "Clear", "Gold", "Gray", "Green", "Multicolor", "Orange", "Pink", "Purple", "Red", "Silver", "White", "Yellow"],
      "Handedness": ["Left-Handed", "Right-Handed"],
    },
  },
  "22966": {
    id: "22966",
    required: ["Brand"],
    values: {
      "Type": ["Acoustic-Electric Guitar"],
      "String Configuration": ["4 String", "5 String", "6 String", "7 String", "8 String", "9 String", "10 String", "12 String"],
      "Body Color": ["Beige", "Black", "Blue", "Brown", "Clear", "Gold", "Gray", "Green", "Multicolor", "Orange", "Pink", "Purple", "Red", "Silver", "White", "Yellow"],
      "Body Type": ["Children's", "Double Neck", "Dreadnought", "Fretless", "Grand Auditorium", "Hollow", "Jumbo", "Semi-Hollow", "Silent", "Solid"],
      "Handedness": ["Left-Handed", "Right-Handed"],
    },
  },
  "33021": {
    id: "33021",
    required: ["Brand"],
    values: {
      "Type": ["Acoustic Guitar"],
      "String Configuration": ["4 String", "5 String", "6 String", "7 String", "8 String", "9 String", "10 String", "12 String"],
      "Body Type": ["Children's", "Double Neck", "Dreadnought", "Fretless", "Grand Auditorium", "Jumbo", "Mini Jumbo", "Parlor"],
      "Handedness": ["Left-Handed", "Right-Handed"],
      "Body Color": ["Beige", "Black", "Blue", "Brown", "Clear", "Gold", "Gray", "Green", "Multicolor", "Orange", "Pink", "Purple", "Red", "Silver", "White", "Yellow"],
    },
  },
  "33034": {
    id: "33034",
    required: ["Brand"],
    values: {
      "Type": ["Electric Guitar"],
      "Body Color": ["Beige", "Black", "Blue", "Brown", "Clear", "Gold", "Gray", "Green", "Multicolor", "Orange", "Pink", "Purple", "Red", "Silver", "White", "Yellow"],
      "Body Type": ["Baritone", "Children's", "Double Neck", "Fretless", "Headless", "Hollow", "Jazz", "Semi-Hollow", "Silent", "Solid"],
      "String Configuration": ["4 String", "5 String", "6 String", "7 String", "8 String", "9 String", "10 String", "12 String"],
      "Handedness": ["Left-Handed", "Right-Handed"],
    },
  },
  "38072": {
    id: "38072",
    required: ["Brand", "Amplifier Type"],
    values: {
      "Amplifier Type": ["Cabinet", "Combo", "Head", "Stack"],
      "Number of Speakers": ["1", "2", "3", "4", "5", "6", "8"],
      "Amplifier Technology": ["Hybrid", "Modeling", "Solid State", "Vacuum Tube"],
    },
  },
};

/** Brand names as eBay spells them. Brand is required in every category. */
export const EBAY_BRANDS: readonly string[] = [
  "Unbranded",
  "Abilene",
  "Ableton",
  "Acronova",
  "Adam Black",
  "Adams Media",
  "ADMIRA",
  "Agile",
  "Aguilar",
  "Akai",
  "AKG",
  "Alba",
  "Alden",
  "Alembic",
  "Alesis",
  "Alessandro",
  "Alexan",
  "Alhambra",
  "Alice",
  "Alpha",
  "Alvarez",
  "Amigo",
  "Ampeg",
  "Antonio Sanchez",
  "Applause",
  "Applecreek",
  "Arbor",
  "Archer",
  "Aria",
  "Art & Lutherie",
  "Artist",
  "Artist Guitars",
  "Ashdown",
  "Ashly",
  "Ashton",
  "Asturias",
  "Audio Zone",
  "Austin",
  "Avatar",
  "Axiom",
  "AXL",
  "Ayers",
  "B.C. Rich",
  "B-52",
  "Bacchus",
  "Bach",
  "Bad Cat",
  "Baker",
  "Bedell",
  "Bedrock",
  "Behringer",
  "Benavente",
  "Best Choice Products",
  "Bigsby",
  "Bill Lawrence",
  "Black Diamond",
  "Blade",
  "Blueridge",
  "Bogen",
  "Bogner",
  "Boss",
  "Bourgeois",
  "Breedlove",
  "Brian May Guitars",
  "Brian Moore",
  "Bridgecraft",
  "Bridges",
  "Brownsville",
  "Budda",
  "Burns",
  "Burny",
  "Burswood",
  "Caparison",
  "Caraya",
  "Carlo Robelli",
  "Carlos Pina",
  "Carr",
  "Carvin",
  "Cashimira Modelo",
  "Casio",
  "Cervantes",
  "Chapman",
  "Charvel",
  "Chord",
  "Clarity",
  "Cleartone",
  "Cole Clark",
  "Collings",
  "Composite Acoustics",
  "Conklin",
  "Cooperstand",
  "Copley",
  "Cordoba",
  "Cort",
  "Cozart",
  "Crafter",
  "Crate",
  "Crescent",
  "Crestwood",
  "Curt Mangan",
  "Custom Guitar Workshop",
  "D'Addario",
  "D'Angelico",
  "D'Aquisto",
  "D&A",
  "Daion",
  "Daisy Rock",
  "Danelectro",
  "DBZ",
  "Dean",
  "Dean Guitars",
  "Dean Markley",
  "DeArmond",
  "Dell'Arte",
  "Diezel",
  "DiGiorgio",
  "DigiTech",
  "Dillion",
  "DiMarzio",
  "Dimavery",
  "DiPinto",
  "Dobro",
  "Don Grosh",
  "Donner",
  "Douglas",
  "Duesenberg",
  "EART",
  "Eastman",
  "Eastwood",
  "Edwards",
  "EKO",
  "Electa",
  "Electra",
  "Electro-Harmonix",
  "Elixir Strings",
  "Emperador",
  "Encore Electronics",
  "Epifani",
  "Epiphone",
  "Epiphone By Gibson",
  "Ernie Ball",
  "Ernie Ball Music Man",
  "ESP",
  "Esp Guitars",
  "Essex",
  "Esteban",
  "ESTEVE",
  "EVH",
  "Faith",
  "Falcon",
  "Fame",
  "Fano",
  "Favilla",
  "Fender",
  "Fender Japan",
  "Fenix",
  "Fernandes",
  "FGN",
  "First Act",
  "Fishman",
  "Flea Bass",
  "Floyd Rose",
  "Fodera",
  "Framus",
  "Freedom",
  "Freshman",
  "Fret-King",
  "Fretlight",
  "FUJIGEN",
  "Furch",
  "G&L",
  "Gallagher",
  "Gallien-Krueger",
  "Galveston",
  "Garcia",
  "Garrision",
  "Gear4music",
  "Germino",
  "GHS",
  "Giannini",
  "Gibson",
  "Gitane",
  "GJ2",
  "Glarry",
  "Glen Burton",
  "Godin",
  "Gold Tone",
  "Goodall",
  "GoPlus",
  "Gordon and Smith",
  "Gould",
  "Goya",
  "Grassroots",
  "Greco",
  "Greg Bennett Design",
  "Gretsch",
  "Grosh",
  "Guild",
  "Guitar Works, Inc.",
  "Guvnor",
  "Guyatone",
  "Gypsy Rose",
  "Hagstrom",
  "Halo",
  "Hamer",
  "Hanika",
  "Harley Benton",
  "Harmony",
  "Hartke",
  "Haze",
  "Headway",
  "HEIDEN",
  "Hercules",
  "Heritage",
  "Hi-Story",
  "Hiwatt",
  "Höfner",
  "HOHNER",
  "Hondo",
  "Hopf",
  "Hoyer",
  "Hudson",
  "Hughes & Kettner",
  "Huntington",
  "Huss & Dalton",
  "Ibanez",
  "Indiana",
  "Indie Guitar",
  "ION",
  "Italia",
  "J & D Luthiers",
  "Jack & Danny",
  "Jackson",
  "Jackson Stars",
  "James Neligan",
  "James Tyler",
  "Jay Turser",
  "JB Player",
  "Jim Dunlop",
  "Jixing",
  "John Pearse",
  "Johnson",
  "Johnson Musical Instruments",
  "José Ramírez",
  "K. Yairi",
  "Kala",
  "Karera",
  "Karrera",
  "Kawai",
  "Kay",
  "Kayne",
  "KEIPER",
  "Keith Urban",
  "Kendrick",
  "Kenny Hill",
  "Ken Smith",
  "King",
  "King Doublebass",
  "Klira",
  "Knaggs",
  "Kona",
  "kramer",
  "Kremona",
  "Ktone",
  "Kustom",
  "La Bella",
  "Lace",
  "Lafayette",
  "LAG",
  "Laguna",
  "Lakewood",
  "Lakland",
  "Laney",
  "La Patrie",
  "Larrivée",
  "La Scala",
  "Legacy",
  "Legator",
  "Legend",
  "Les Paul",
  "Levin",
  "Lindo",
  "Line 6",
  "Lotus",
  "Lowden",
  "Lucero",
  "Lucida",
  "LUNA",
  "LyxPro",
  "Maccaferri",
  "Maestro",
  "Magnatone",
  "Magnum",
  "Manson",
  "Manuel Rodríguez",
  "Marquez",
  "Marshall",
  "Martin",
  "Martinez",
  "Martin Guitars",
  "Maton",
  "Maxam",
  "Maybach",
  "Mayones",
  "Mcpherson",
  "MEINL",
  "Memphis",
  "Mesa Boogie",
  "Michael Kelly",
  "Mike Lull",
  "Minarik",
  "Ministar",
  "Mitchell",
  "Modulus",
  "Momose",
  "Monterey",
  "MOOG",
  "Moon",
  "Morgan Monroe",
  "Morris",
  "Mosrite",
  "Mossman",
  "MTD",
  "Mullard",
  "Musician's Gear",
  "Music Man",
  "Music Man / OLP",
  "Musima",
  "Nash",
  "National",
  "Navigator",
  "Nobels",
  "Norman",
  "Not Just Stands",
  "NS Design",
  "Off The Wall",
  "OLP",
  "Olson",
  "Olympia",
  "On-Stage Stands",
  "Onyx",
  "Ortega",
  "Orville by Gibson",
  "Oscar Schmidt",
  "Ovation",
  "Parker",
  "Parker Guitars",
  "Patrick Eggle",
  "Paul Stanley",
  "PEAK MUSIC STANDS",
  "Peal",
  "Pearl",
  "Peavey",
  "Pedulla",
  "Pignose",
  "Playtech",
  "Poynter",
  "PRS",
  "Pyle",
  "RainSong",
  "Ramirez",
  "RC Strings",
  "Recording King",
  "Regal",
  "Revelation",
  "Reverend",
  "Reynolds",
  "Richwood",
  "Rickenbacker",
  "Rick Turner",
  "Robin",
  "Rockinger",
  "Rocktile",
  "Rocktron",
  "Rogue",
  "Roland",
  "Roscoe",
  "Rosetti",
  "Rotosound",
  "S.Yairi",
  "Sadowsky",
  "Saga",
  "Samick",
  "Sanatoga",
  "Sanchez",
  "Sandberg",
  "Santa Cruz",
  "SAVAREZ",
  "Sawtooth",
  "Schafer",
  "Schaller",
  "Schecter",
  "Schertler",
  "Seagull",
  "Selmer",
  "Seymour Duncan",
  "Shaftesbury",
  "Shine",
  "Shredneck",
  "Sigma",
  "Silhouette",
  "Silver Creek",
  "Silverstone",
  "Silvertone",
  "Simon & Patrick",
  "Skervesen",
  "Skylark",
  "Soldano",
  "Spector",
  "Squier",
  "Squier by Fender",
  "Squiere",
  "Squire",
  "Stageline",
  "Stagg",
  "Status",
  "Steinberger",
  "Sterling",
  "Sterling by Music Man",
  "strandberg",
  "Sugi",
  "Suhr",
  "Sukop",
  "Sunlite",
  "Supro",
  "Suzuki",
  "SWR",
  "SX",
  "Synsonics",
  "Tacoma",
  "Tagima",
  "Takamine",
  "Tanglewood",
  "TASCAM",
  "Taylor",
  "Teisco",
  "Tenson",
  "Téo Jasmin",
  "TETON Sports",
  "The Loar",
  "Tobias",
  "Tokai",
  "Tom Anderson",
  "Traben Bass Company",
  "Trace Elliot",
  "Traveler",
  "Traveler Guitar",
  "Trinity River",
  "Truetone",
  "Tune",
  "Two-Rock",
  "U.S. Masters",
  "Ultimate Support",
  "Ultra Case",
  "Univox",
  "Valencia",
  "Valley Arts",
  "VENTURA",
  "VESTER",
  "Victoria",
  "Vintage",
  "Vox",
  "Voyage-Air",
  "Wal",
  "Walden",
  "Warmoth",
  "Warwick",
  "Washburn",
  "Waterstone",
  "Weber",
  "Wechter",
  "Weissenborn",
  "Wesley",
  "Westfield",
  "Westone",
  "Wido",
  "Wolf",
  "Woodstock",
  "Xaviere",
  "Xotic",
  "Yamaha",
  "YAMAKI",
  "Yorkville",
  "Zager",
  "Zemaitis",
  "ZENY",
  "ZIVIX",
  "Zon",
  "Zoom",
];
