// GENERATED FILE -- do not edit by hand.
// Regenerate with: node scripts/fetch-sweetwater-vocabulary.mjs
// Pulled from Sweetwater's public Gear Exchange Algolia index on 2026-08-05.

export interface SweetwaterCategory {
  code: string;
  label: string;
}

export interface SweetwaterSubcategory extends SweetwaterCategory {
  /** code of the owning top-level category */
  top: string;
}

export const TOP_CATEGORIES: readonly SweetwaterCategory[] = [
  { code: "guitars", label: "Guitars" },
  { code: "effects-and-pedals", label: "Effects & Pedals" },
  { code: "amplifiers", label: "Amplifiers" },
  { code: "bass-gear", label: "Bass" },
  { code: "keyboards-and-synthesizers", label: "Keyboards & Synthesizers" },
  { code: "microphones-and-wireless", label: "Microphones & Wireless" },
  { code: "live-sound-and-lighting", label: "Live Sound & Lighting" },
  { code: "studio-recording-gear", label: "Studio & Recording Gear" },
  { code: "drums-and-percussion", label: "Drum & Percussion" },
  { code: "band-and-orchestra", label: "Band & Orchestra" },
  { code: "dj-electronic", label: "DJ / Electronic" },
  { code: "folk-instruments", label: "Folk Instruments" },
];

export const SUBCATEGORIES: readonly SweetwaterSubcategory[] = [
  { code: "amp-accessories", label: "Amp Accessories", top: "amplifiers" },
  { code: "bass-amp-accessories", label: "Bass Amp Accessories", top: "amplifiers" },
  { code: "bass-guitar-amps", label: "Bass Guitar Amps", top: "amplifiers" },
  { code: "guitar-amps", label: "Guitar Amps", top: "amplifiers" },
  { code: "other-amplifiers", label: "Other Amplifiers", top: "amplifiers" },
  { code: "bass-amp-cabinets", label: "Bass Amp Cabinets", top: "amplifiers" },
  { code: "bass-amp-heads", label: "Bass Amp Heads", top: "amplifiers" },
  { code: "bass-combo-amps", label: "Bass Combo Amps", top: "amplifiers" },
  { code: "guitar-amp-cabinets", label: "Guitar Amp Cabinets", top: "amplifiers" },
  { code: "guitar-amp-heads", label: "Guitar Amp Heads", top: "amplifiers" },
  { code: "guitar-combo-amps", label: "Guitar Combo Amps", top: "amplifiers" },
  { code: "brass-instruments", label: "Brass Instruments", top: "band-and-orchestra" },
  { code: "concert-percussion", label: "Concert Percussion", top: "band-and-orchestra" },
  { code: "marching-percussion", label: "Marching Percussion", top: "band-and-orchestra" },
  { code: "orchestral-string-instruments", label: "Orchestral String Instruments", top: "band-and-orchestra" },
  { code: "other-band-and-orchestra", label: "Other Band & Orchestra", top: "band-and-orchestra" },
  { code: "woodwind-instruments", label: "Woodwind Instruments", top: "band-and-orchestra" },
  { code: "alto-and-tenor-horns", label: "Alto & Tenor Horns", top: "band-and-orchestra" },
  { code: "baritone-horns", label: "Baritone Horns", top: "band-and-orchestra" },
  { code: "bassoons", label: "Bassoons", top: "band-and-orchestra" },
  { code: "bells-and-glockenspiels", label: "Bells & Glockenspiels", top: "band-and-orchestra" },
  { code: "bows", label: "Bows", top: "band-and-orchestra" },
  { code: "brass-accessories", label: "Brass Accessories", top: "band-and-orchestra" },
  { code: "brass-cases-covers-and-bags", label: "Brass Cases, Covers, & Bags", top: "band-and-orchestra" },
  { code: "brass-mouthpieces", label: "Brass Mouthpieces", top: "band-and-orchestra" },
  { code: "bugles", label: "Bugles", top: "band-and-orchestra" },
  { code: "cellos", label: "Cellos", top: "band-and-orchestra" },
  { code: "clarinets", label: "Clarinets", top: "band-and-orchestra" },
  { code: "concert-snare-drums", label: "Concert Snare Drums", top: "band-and-orchestra" },
  { code: "concert-toms", label: "Concert Toms", top: "band-and-orchestra" },
  { code: "cornets", label: "Cornets", top: "band-and-orchestra" },
  { code: "double-bass", label: "Double Bass", top: "band-and-orchestra" },
  { code: "euphoniums", label: "Euphoniums", top: "band-and-orchestra" },
  { code: "flugelhorns", label: "Flugelhorns", top: "band-and-orchestra" },
  { code: "flutes", label: "Flutes", top: "band-and-orchestra" },
  { code: "french-horns", label: "French Horns", top: "band-and-orchestra" },
  { code: "hand-and-mounted-percussion", label: "Hand & Mounted Percussion", top: "band-and-orchestra" },
  { code: "harps", label: "Harps", top: "band-and-orchestra" },
  { code: "marching-bass-drums", label: "Marching Bass Drums", top: "band-and-orchestra" },
  { code: "marimbas", label: "Marimbas", top: "band-and-orchestra" },
  { code: "mellophones", label: "Mellophones", top: "band-and-orchestra" },
  { code: "music-stands", label: "Music Stands", top: "band-and-orchestra" },
  { code: "oboes", label: "Oboes", top: "band-and-orchestra" },
  { code: "orchestral-accessories", label: "Orchestral Accessories", top: "band-and-orchestra" },
  { code: "piccolos", label: "Piccolos", top: "band-and-orchestra" },
  { code: "saxophones", label: "Saxophones", top: "band-and-orchestra" },
  { code: "trombones", label: "Trombones", top: "band-and-orchestra" },
  { code: "trumpets", label: "Trumpets", top: "band-and-orchestra" },
  { code: "tubas", label: "Tubas", top: "band-and-orchestra" },
  { code: "vibraphones", label: "Vibraphones", top: "band-and-orchestra" },
  { code: "violas", label: "Violas", top: "band-and-orchestra" },
  { code: "violins", label: "Violins", top: "band-and-orchestra" },
  { code: "woodwind-accessories", label: "Woodwind Accessories", top: "band-and-orchestra" },
  { code: "woodwind-cases-covers-and-bags", label: "Woodwind Cases, Covers, & Bags", top: "band-and-orchestra" },
  { code: "woodwind-mouthpieces", label: "Woodwind Mouthpieces", top: "band-and-orchestra" },
  { code: "xylophones", label: "Xylophones", top: "band-and-orchestra" },
  { code: "bass-guitar-accessories", label: "Bass Guitar Accessories", top: "bass-gear" },
  { code: "bass-guitar-pickups", label: "Bass Guitar Pickups", top: "bass-gear" },
  { code: "bass-guitars", label: "Bass Guitars", top: "bass-gear" },
  { code: "guitar-wireless-systems", label: "Guitar Wireless Systems", top: "bass-gear" },
  { code: "other-bass-guitar", label: "Other Bass Guitar", top: "bass-gear" },
  { code: "4-string-bass-guitars", label: "4-string Bass Guitars", top: "bass-gear" },
  { code: "5-string-bass-guitars", label: "5-string Bass Guitars", top: "bass-gear" },
  { code: "6-string-bass-guitars", label: "6+ string Bass Guitars", top: "bass-gear" },
  { code: "acoustic-bass-guitars", label: "Acoustic Bass Guitars", top: "bass-gear" },
  { code: "bass-guitar-cases", label: "Bass Guitar Cases", top: "bass-gear" },
  { code: "fretless-bass-guitars", label: "Fretless Bass Guitars", top: "bass-gear" },
  { code: "beat-production", label: "Beat Production", top: "dj-electronic" },
  { code: "dj-accessories", label: "DJ Accessories", top: "dj-electronic" },
  { code: "dj-controllers", label: "DJ Controllers", top: "dj-electronic" },
  { code: "dj-effects", label: "DJ Effects", top: "dj-electronic" },
  { code: "dj-headphones", label: "DJ Headphones", top: "dj-electronic" },
  { code: "dj-media-players", label: "DJ Media Players", top: "dj-electronic" },
  { code: "dj-mixers", label: "DJ Mixers", top: "dj-electronic" },
  { code: "dj-turntables", label: "DJ Turntables", top: "dj-electronic" },
  { code: "midi-controllers", label: "MIDI Controllers", top: "dj-electronic" },
  { code: "other-dj-electronic", label: "Other DJ / Electronic", top: "dj-electronic" },
  { code: "pa-systems-and-speakers", label: "PA Systems & Speakers", top: "dj-electronic" },
  { code: "turntables-and-accessories", label: "Turntables & Accessories", top: "dj-electronic" },
  { code: "sequencers", label: "Sequencers", top: "dj-electronic" },
  { code: "acoustic-drums", label: "Acoustic Drums", top: "drums-and-percussion" },
  { code: "cymbals", label: "Cymbals", top: "drums-and-percussion" },
  { code: "drum-and-percussion-accessories", label: "Drum & Percussion Accessories", top: "drums-and-percussion" },
  { code: "drum-hardware", label: "Drum Hardware", top: "drums-and-percussion" },
  { code: "electronic-drums", label: "Electronic Drums", top: "drums-and-percussion" },
  { code: "hand-drums", label: "Hand Drums", top: "drums-and-percussion" },
  { code: "other-drum-and-percussion", label: "Other Drum & Percussion", top: "drums-and-percussion" },
  { code: "world-percussion", label: "World Percussion", top: "drums-and-percussion" },
  { code: "acoustic-drum-sets", label: "Acoustic Drum Sets", top: "drums-and-percussion" },
  { code: "bass-drums", label: "Bass Drums", top: "drums-and-percussion" },
  { code: "bongos", label: "Bongos", top: "drums-and-percussion" },
  { code: "cajons", label: "Cajons", top: "drums-and-percussion" },
  { code: "china-cymbals", label: "China Cymbals", top: "drums-and-percussion" },
  { code: "congas", label: "Congas", top: "drums-and-percussion" },
  { code: "cowbells", label: "Cowbells", top: "drums-and-percussion" },
  { code: "crash-cymbals", label: "Crash Cymbals", top: "drums-and-percussion" },
  { code: "cymbal-packs", label: "Cymbal Packs", top: "drums-and-percussion" },
  { code: "djembes", label: "Djembes", top: "drums-and-percussion" },
  { code: "drum-accessory-hardware", label: "Drum Accessory Hardware", top: "drums-and-percussion" },
  { code: "drum-amplifiers", label: "Drum Amplifiers", top: "drums-and-percussion" },
  { code: "drum-cases-and-bags", label: "Drum Cases & Bags", top: "drums-and-percussion" },
  { code: "drum-clamps", label: "Drum Clamps", top: "drums-and-percussion" },
  { code: "drum-heads", label: "Drum Heads", top: "drums-and-percussion" },
  { code: "drum-keys-and-tuning-tools", label: "Drum Keys & Tuning Tools", top: "drums-and-percussion" },
  { code: "drum-machines-and-samplers", label: "Drum Machines & Samplers", top: "drums-and-percussion" },
  { code: "drum-mutes-and-dampening-devices", label: "Drum Mutes & Dampening Devices", top: "drums-and-percussion" },
  { code: "drum-pedals-and-beaters", label: "Drum Pedals & Beaters", top: "drums-and-percussion" },
  { code: "drum-practice-pads", label: "Drum Practice Pads", top: "drums-and-percussion" },
  { code: "drum-replacement-parts", label: "Drum Replacement Parts", top: "drums-and-percussion" },
  { code: "drum-shields", label: "Drum Shields", top: "drums-and-percussion" },
  { code: "drum-stands-and-mounts", label: "Drum Stands & Mounts", top: "drums-and-percussion" },
  { code: "drum-thrones", label: "Drum Thrones", top: "drums-and-percussion" },
  { code: "drum-triggers-and-pads", label: "Drum Triggers & Pads", top: "drums-and-percussion" },
  { code: "drumsticks-mallets-and-brushes", label: "Drumsticks, Mallets & Brushes", top: "drums-and-percussion" },
  { code: "electronic-cymbal-pads", label: "Electronic Cymbal Pads", top: "drums-and-percussion" },
  { code: "electronic-drum-controllers-and-multipads", label: "Electronic Drum Controllers & Multipads", top: "drums-and-percussion" },
  { code: "electronic-drum-modules", label: "Electronic Drum Modules", top: "drums-and-percussion" },
  { code: "electronic-drum-sets", label: "Electronic Drum Sets", top: "drums-and-percussion" },
  { code: "floor-toms", label: "Floor Toms", top: "drums-and-percussion" },
  { code: "hand-drum-accessories", label: "Hand Drum Accessories", top: "drums-and-percussion" },
  { code: "hi-hat-cymbals", label: "Hi-hat Cymbals", top: "drums-and-percussion" },
  { code: "kalimbas", label: "Kalimbas", top: "drums-and-percussion" },
  { code: "mounted-toms", label: "Mounted Toms", top: "drums-and-percussion" },
  { code: "ride-cymbals", label: "Ride Cymbals", top: "drums-and-percussion" },
  { code: "shakers", label: "Shakers", top: "drums-and-percussion" },
  { code: "snare-drums", label: "Snare Drums", top: "drums-and-percussion" },
  { code: "specialty-drums", label: "Specialty Drums", top: "drums-and-percussion" },
  { code: "splash-cymbals", label: "Splash Cymbals", top: "drums-and-percussion" },
  { code: "tambourines", label: "Tambourines", top: "drums-and-percussion" },
  { code: "timbales", label: "Timbales", top: "drums-and-percussion" },
  { code: "acoustic-guitar-effects", label: "Acoustic Guitar Effects", top: "effects-and-pedals" },
  { code: "amp-and-cabinet-simulators", label: "Amp & Cabinet Simulators", top: "effects-and-pedals" },
  { code: "bass-pedals", label: "Bass Pedals", top: "effects-and-pedals" },
  { code: "chorus-pedals", label: "Chorus Pedals", top: "effects-and-pedals" },
  { code: "compressor-and-eq-pedals", label: "Compressor and EQ Pedals", top: "effects-and-pedals" },
  { code: "distortion-overdrive-boost-and-fuzz", label: "Distortion, Overdrive, Boost & Fuzz", top: "effects-and-pedals" },
  { code: "flanger-pedals", label: "Flanger Pedals", top: "effects-and-pedals" },
  { code: "footswitch-and-selector-pedals", label: "Footswitch and Selector Pedals", top: "effects-and-pedals" },
  { code: "guitar-preamps", label: "Guitar Preamps", top: "effects-and-pedals" },
  { code: "harmony-pedals-and-processors", label: "Harmony Pedals & Processors", top: "effects-and-pedals" },
  { code: "looper-pedals", label: "Looper Pedals", top: "effects-and-pedals" },
  { code: "multi-effects-pedals", label: "Multi-Effects Pedals", top: "effects-and-pedals" },
  { code: "noise-gate-and-suppressor-pedals", label: "Noise Gate & Suppressor Pedals", top: "effects-and-pedals" },
  { code: "other-effects", label: "Other Effects", top: "effects-and-pedals" },
  { code: "pedal-accessories", label: "Pedal Accessories", top: "effects-and-pedals" },
  { code: "pedalboards-and-power-supplies", label: "Pedalboards and Power Supplies", top: "effects-and-pedals" },
  { code: "phaser-pedals", label: "Phaser Pedals", top: "effects-and-pedals" },
  { code: "reverb-and-delay-pedals", label: "Reverb and Delay Pedals", top: "effects-and-pedals" },
  { code: "synth-pedals", label: "Synth Pedals", top: "effects-and-pedals" },
  { code: "tremolo-pedals", label: "Tremolo Pedals", top: "effects-and-pedals" },
  { code: "volume-and-expression-pedals", label: "Volume and Expression Pedals", top: "effects-and-pedals" },
  { code: "wah-and-filter-pedals", label: "Wah and Filter Pedals", top: "effects-and-pedals" },
  { code: "banjos", label: "Banjos", top: "folk-instruments" },
  { code: "folk-instrument-accessories", label: "Folk Instrument Accessories", top: "folk-instruments" },
  { code: "mandolins", label: "Mandolins", top: "folk-instruments" },
  { code: "other-folk-instruments", label: "Other Folk Instruments", top: "folk-instruments" },
  { code: "ukuleles", label: "Ukuleles", top: "folk-instruments" },
  { code: "acoustic-guitars", label: "Acoustic Guitars", top: "guitars" },
  { code: "electric-guitars", label: "Electric Guitars", top: "guitars" },
  { code: "guitar-accessories", label: "Guitar Accessories", top: "guitars" },
  { code: "guitar-parts", label: "Guitar Parts", top: "guitars" },
  { code: "other-guitar", label: "Other Guitar", top: "guitars" },
  { code: "12-string-guitars", label: "12-string Guitars", top: "guitars" },
  { code: "6-string-guitars", label: "6-string Guitars", top: "guitars" },
  { code: "guitar-cables", label: "Guitar Cables", top: "guitars" },
  { code: "guitar-capos", label: "Guitar Capos", top: "guitars" },
  { code: "guitar-cases-and-gig-bags", label: "Guitar Cases and Gig Bags", top: "guitars" },
  { code: "guitar-pickguards", label: "Guitar Pickguards", top: "guitars" },
  { code: "guitar-pickups", label: "Guitar Pickups", top: "guitars" },
  { code: "guitar-slides", label: "Guitar Slides", top: "guitars" },
  { code: "guitar-stands", label: "Guitar Stands", top: "guitars" },
  { code: "guitar-straps", label: "Guitar Straps", top: "guitars" },
  { code: "guitar-tuners", label: "Guitar Tuners", top: "guitars" },
  { code: "hollowbody-guitars", label: "Hollowbody Guitars", top: "guitars" },
  { code: "replacement-guitar-necks", label: "Replacement Guitar Necks", top: "guitars" },
  { code: "semi-hollow-guitars", label: "Semi-Hollow Guitars", top: "guitars" },
  { code: "solidbody-guitars", label: "Solidbody Guitars", top: "guitars" },
  { code: "accordions", label: "Accordions", top: "keyboards-and-synthesizers" },
  { code: "electric-organs", label: "Electric Organs", top: "keyboards-and-synthesizers" },
  { code: "eurorack-and-modular-synths", label: "Eurorack & Modular Synths", top: "keyboards-and-synthesizers" },
  { code: "eurorack-modular-synths", label: "Eurorack Modular Synths", top: "keyboards-and-synthesizers" },
  { code: "keyboard-accessories", label: "Keyboard Accessories", top: "keyboards-and-synthesizers" },
  { code: "keyboard-amplifiers", label: "Keyboard Amplifiers", top: "keyboards-and-synthesizers" },
  { code: "keyboard-workstations", label: "Keyboard Workstations", top: "keyboards-and-synthesizers" },
  { code: "other-keyboards-and-synthesizers", label: "Other Keyboards & Synthesizers", top: "keyboards-and-synthesizers" },
  { code: "pianos", label: "Pianos", top: "keyboards-and-synthesizers" },
  { code: "portable-and-arranger-keyboards", label: "Portable & Arranger Keyboards", top: "keyboards-and-synthesizers" },
  { code: "synthesizers", label: "Synthesizers", top: "keyboards-and-synthesizers" },
  { code: "eurorack-modules", label: "Eurorack Modules", top: "keyboards-and-synthesizers" },
  { code: "direct-boxes", label: "Direct Boxes", top: "live-sound-and-lighting" },
  { code: "essential-audio-tools", label: "Essential Audio Tools", top: "live-sound-and-lighting" },
  { code: "lighting", label: "Lighting", top: "live-sound-and-lighting" },
  { code: "live-sound-mixers", label: "Live Sound Mixers", top: "live-sound-and-lighting" },
  { code: "live-sound-monitoring", label: "Live Sound Monitoring", top: "live-sound-and-lighting" },
  { code: "other-live-sound-and-lighting", label: "Other Live Sound & Lighting", top: "live-sound-and-lighting" },
  { code: "portable-racks-and-cases", label: "Portable Racks & Cases", top: "live-sound-and-lighting" },
  { code: "power-amplifiers", label: "Power Amplifiers", top: "live-sound-and-lighting" },
  { code: "power-supplies", label: "Power Supplies", top: "live-sound-and-lighting" },
  { code: "staging", label: "Staging", top: "live-sound-and-lighting" },
  { code: "condenser-microphones", label: "Condenser Microphones", top: "microphones-and-wireless" },
  { code: "drum-microphones", label: "Drum Microphones", top: "microphones-and-wireless" },
  { code: "dynamic-microphones", label: "Dynamic Microphones", top: "microphones-and-wireless" },
  { code: "headset-microphones", label: "Headset Microphones", top: "microphones-and-wireless" },
  { code: "ipad-iphone-microphones", label: "iPad/iPhone Microphones", top: "microphones-and-wireless" },
  { code: "lavalier-microphones", label: "Lavalier Microphones", top: "microphones-and-wireless" },
  { code: "microphone-accessories", label: "Microphone Accessories", top: "microphones-and-wireless" },
  { code: "other-microphones-and-wireless", label: "Other Microphones & Wireless", top: "microphones-and-wireless" },
  { code: "ribbon-microphones", label: "Ribbon Microphones", top: "microphones-and-wireless" },
  { code: "shotgun-microphones", label: "Shotgun Microphones", top: "microphones-and-wireless" },
  { code: "usb-microphones", label: "USB Microphones", top: "microphones-and-wireless" },
  { code: "wireless-systems", label: "Wireless Systems", top: "microphones-and-wireless" },
  { code: "audio-interfaces", label: "Audio Interfaces", top: "studio-recording-gear" },
  { code: "headphones", label: "Headphones", top: "studio-recording-gear" },
  { code: "other-recording-gear", label: "Other Recording Gear", top: "studio-recording-gear" },
  { code: "preamps-and-channel-strips", label: "Preamps & Channel Strips", top: "studio-recording-gear" },
  { code: "recorders", label: "Recorders", top: "studio-recording-gear" },
  { code: "signal-processing", label: "Signal Processing", top: "studio-recording-gear" },
  { code: "studio-furniture-and-acoustic-treatment", label: "Studio Furniture & Acoustic Treatment", top: "studio-recording-gear" },
  { code: "studio-mixers-and-control-surfaces", label: "Studio Mixers & Control Surfaces", top: "studio-recording-gear" },
  { code: "studio-monitors", label: "Studio Monitors", top: "studio-recording-gear" },
  { code: "video-equipment", label: "Video Equipment", top: "studio-recording-gear" },
];

/** Brand names as Sweetwater spells them, most-listed first. */
export const BRANDS: readonly string[] = [
  "Fender",
  "Gibson",
  "Yamaha",
  "Epiphone",
  "Shure",
  "Ibanez",
  "PRS",
  "Boss",
  "Roland",
  "Squier",
  "Sennheiser",
  "Gretsch",
  "Jackson",
  "Martin",
  "Chauvet",
  "Electro-Harmonix",
  "Taylor",
  "Behringer",
  "Schecter",
  "JBL",
  "Peavey",
  "Zildjian",
  "Studer",
  "MXR",
  "ESP",
  "Line 6",
  "Marshall",
  "Universal Audio",
  "Korg",
  "Ludwig",
  "G&L",
  "Elation",
  "Clear-Com",
  "Solid State Logic",
  "Allen & Heath",
  "PreSonus",
  "Sabian",
  "EVH",
  "Pearl",
  "Alesis",
  "Audio-Technica",
  "Fender Custom Shop",
  "Charvel",
  "Guild",
  "QSC",
  "Ernie Ball Music Man",
  "AKG",
  "DW",
  "Ernie Ball",
  "Sylvania",
  "TAMA",
  "Vox",
  "Remo",
  "JHS",
  "Seymour Duncan",
  "Rickenbacker",
  "Washburn",
  "Electro-Voice (EV)",
  "Dunlop",
  "Akai Professional",
  "Avid",
  "Mackie",
  "Warm Audio",
  "Schaller",
  "Walrus Audio",
  "EAW",
  "TC Electronic",
  "The Analog Source",
  "dbx",
  "Crown",
  "Danelectro",
  "Dean",
  "Digitech",
  "Reverend",
  "DOD",
  "Gator",
  "RCA",
  "BSS",
  "Pioneer DJ",
  "Greco",
  "Martin Lighting",
  "RTS",
  "Zoom",
  "Mesa/Boogie",
  "Meyer Sound",
  "Alvarez",
  "Ampeg",
  "DiMarzio",
  "Harmony",
  "N/A",
  "Rode",
  "Focusrite",
  "Keeley",
  "Friedman",
  "ART",
  "Carpenter Studio Gear",
  "Lab Gruppen",
  "Native Instruments",
  "Selmer",
  "Aviom",
  "Kramer",
  "D'Angelico",
  "G.E",
  "Strymon",
  "Supro",
  "Tascam",
  "EarthQuaker Devices",
  "Mogami",
  "Samson",
  "Sterling",
  "Tokai",
  "ADJ",
  "Breedlove",
  "IK Multimedia",
  "Suhr",
  "Chauvet DJ",
  "Wampler",
  "Ovation",
  "Paiste",
  "Silvertone",
  "Warwick",
  "Electro-Voice",
  "Neumann",
  "Blackstar",
  "Grover",
  "Philips",
  "Soundcraft",
  "Takamine",
  "ESP LTD",
  "Kay",
  "Lone Buck Guitars",
  "Novation",
  "Catalinbread",
  "Klark Teknik",
  "Moog",
  "Cort",
  "Digidesign",
  "Guyatone",
  "Heritage",
  "M-Audio",
  "Midas",
  "Selmer Paris",
  "Donner",
  "Electro Voice",
  "Spector",
  "Teisco",
  "Bose",
  "G-Tech Guitar Works",
  "Golden Age",
  "MOOER",
  "National",
  "Orange",
  "Pro Co",
  "Casio",
  "Fulltone",
  "Gibson Acoustic",
  "Meinl Cymbals",
  "Whirlwind",
  "Ashly",
  "D'Addario",
  "Eartec",
  "Hofner",
  "tonal eclipse",
  "Carvin",
  "Celestion",
  "Gibraltar",
  "Gibson Custom",
  "Kluson",
  "SILVER SKY MOD SHOP",
  "Eastman",
  "Gemeinhardt",
  "Hohner",
  "Aria",
  "EART",
  "Larrivee",
  "B.C. RICH",
  "Eventide",
  "Joyo",
  "Morley",
  "Parker",
  "Altman",
  "Arturia",
  "Audix",
  "Collings",
  "Custom",
  "EL Jefe Guitars",
  "Godin",
  "Hosa",
  "Latin Percussion",
  "Pigtronix",
  "Apogee",
  "Burny",
  "NUX",
  "Rane",
  "SONOR",
  "Furman",
  "MOTU",
  "Radial",
  "Sire",
  "Source Audio",
  "Armstrong",
  "Blackmagic Design",
  "Buffet Crampon",
  "Crest Audio",
  "Fishman",
  "J. Rockett Audio Designs",
  "Jensen",
  "Maestro",
  "Numark",
  "SKB",
  "Conn",
  "Crate",
  "Digital Audio Labs",
  "EMG",
  "Hagstrom",
  "Hartke",
  "Mapex",
  "Orville",
  "Slingerland",
  "Sony",
  "Strandberg",
  "Arion",
  "Cordoba",
  "Haggtronix",
  "Kiesel",
  "Rolls",
  "SLS",
  "Sterling By Music Man",
  "Aguilar",
  "Ashdown",
  "Audinate",
  "Blizzard Lighting",
  "Bogner",
  "Hamer",
  "Jupiter",
  "Tech 21",
  "Two Notes",
  "Univox",
  "Vola Guitars",
  "American DJ",
  "BBE",
  "Electra",
  "Gretsch Drums",
  "Hughes & Kettner",
  "Kawai",
  "LTD by ESP",
  "Loop-Master Pedals",
  "Mosrite",
  "On-Stage",
  "PDP",
  "Rocktron",
  "Sadowsky",
  "Slate Digital",
  "Warmoth",
  "Waves",
  "Bach",
  "Carmedon",
  "Darkglass",
  "DeArmond",
  "Earthworks",
  "Jackson Audio",
  "Lectrosonics",
  "Lovepedal",
  "None",
  "Void",
  "Amperex",
  "Audient",
  "Blue Microphones",
  "Bourgeois",
  "Denon",
  "Framus",
  "Furch",
  "Hear Technologies",
  "JumperZ",
  "Kemper",
  "Laney",
  "Maxon",
  "Pedaltrain",
  "Proper Instruments",
  "Radial Engineering",
  "Rogers",
  "Vandoren",
  "Airline",
  "Aria Pro II",
  "Dangerous Music",
  "Dortron",
  "Dr. Z",
  "Evans",
  "Fernandes",
  "Gallien-Krueger",
  "Holton",
  "Sequential",
  "Symetrix",
  "Telex",
  "Way Huge",
  "ADAM Audio",
  "Adamson",
  "Antelope Audio",
  "Digico",
  "Firefly",
  "Gemini",
  "K-Array",
  "KRK",
  "Mesa Boogie",
  "Michael Kelly",
  "Pelican",
  "Positive Grid",
  "Rafferty",
  "Rupert Neve Designs",
  "SPL",
  "Seismic Audio",
  "Simmons",
  "Softube",
  "T-Rex",
  "Theo Wanne",
  "sE Electronics",
  "API",
  "Acoustic",
  "Analysis Plus",
  "Avalon",
  "Bad Cat",
  "Buescher",
  "Duesenberg",
  "Eastman Guitars",
  "Gold Tone",
  "Hammond",
  "Kent",
  "King",
  "Kustom",
  "Lowden",
  "Music Man",
  "Origin Effects",
  "Premier",
  "SWR",
  "Singular Sound",
  "Steinberger",
  "TKL",
  "Telefunken",
  "Trace Elliot",
  "Victory Amplification",
  "Vito",
  "Anchor Audio",
  "AudioScience",
  "Bittree",
  "Black Diamond",
  "Chroma-Q",
  "EBS",
  "Eko",
  "Eminence",
  "Empress Effects",
  "Generic",
  "HME",
  "Middle Atlantic Products",
  "Monster Cable",
  "Morris",
  "Nate's Relic Guitars",
  "No Brand",
  "Olds",
  "Pioneer",
  "Revv",
  "Reynolds",
  "Robert Juliat",
  "Rockville",
  "SGM",
  "Squire",
  "Synergy",
  "Vertex Effects",
  "Yanagisawa",
  "beyerdynamic",
  "d&b audiotechnik",
  "Bugera",
  "DPA",
  "E-MU",
  "Edwards",
  "Elektron",
  "First Act",
  "Fractal audio",
  "Heritage Audio",
  "Hotone",
  "Kogoy Musical Devices",
  "Leblanc",
  "MA Lighting",
  "MIPRO",
  "Magnatone",
  "Marantz",
  "Martin Audio",
  "Meinl Percussion",
  "Monster",
  "NEXO",
  "Ortega",
  "Orville by Gibson",
  "Recording King",
  "Samick",
  "Switchcraft",
  "TC-Helicon",
  "Vic Firth",
  "Vintage",
  "Voodoo Lab",
  "CAD",
  "Chandler Limited",
  "Drawmer",
  "Fender Accessories",
  "Galaxy Audio",
  "Hondo",
  "Kala",
  "MXL",
  "Manley",
  "Meris",
  "Motorola",
  "NS Design",
  "Odyssey",
  "Pivitec",
  "ProCo",
  "ProX",
  "Rhythm Tech",
  "Rogue",
  "Soldano",
  "Studiologic",
  "Tung-Sol",
  "UKing",
  "Vega",
  "WattBox",
  "Wren and Cuff",
  "dBTechnologies",
  "ddrum",
  "AKAI",
  "AlphaTheta",
  "Analogman",
  "Ape Labs",
  "Atlas Sound",
  "Audio Technica",
  "Benson Amps",
  "Caline",
  "Carl Martin",
  "Crestron",
  "Ensoniq",
  "Gotoh",
  "Graph Tech",
  "Harley Benton",
  "Kurzweil",
  "L.P.",
  "Lewitt",
  "McCauley",
  "Mission Engineering",
  "Mojave Audio",
  "Multivox",
  "Nash Guitars",
  "Nord",
  "Oahu",
  "On-Stage Stands",
  "RAPCO",
  "RDL",
  "Radiall / Larsen",
  "Randall",
  "Road Runner",
  "Rosco",
  "Sabine",
  "Suzuki",
  "TOA",
  "Teac",
  "Thomas Organ",
  "Townsend Labs",
  "VUE Audiotechnik",
  "ZVEX",
  "Ace",
  "Austin",
  "Brilhart",
  "Cerberus",
  "Chase Bliss",
  "Clay Paky",
  "Darkglass Electronics",
  "Death By Audio",
  "Deering",
  "Dobro",
  "Egnater",
  "Emerson",
  "Flight",
  "Focal",
  "Gamma",
  "Golden Age Project",
  "Headrush",
  "Hiwatt",
  "K&M",
  "Leslie",
  "Lexicon",
  "MEGA-LITE",
  "Maton",
  "Maybach",
  "Microframe",
  "Mitchell",
  "Monkey Riot",
  "Nady",
  "Nektar",
  "Oberheim",
  "Oscar Schmidt",
  "Other (Miscellanous Used/Vintage/Consign)",
  "Ozona Guitar Works",
  "Peterson",
  "Point Source Audio",
  "Pro Intercom",
  "RCF",
  "RME",
  "Rick Turner",
  "Roscoe",
  "Ross",
  "Santa Cruz",
  "Solomon",
  "Valeton",
  "Various",
  "Waldorf",
  "Xta Electronics",
  "Xvive",
  "Zager",
  "elysia",
  "1010music",
  "3D Printed",
  "Airwave Technologies",
  "Alamo",
  "Ampex",
  "Amplified Nation",
  "Artley",
  "Ash Custom Design Co.",
  "Avantone Pro",
  "BBanalog",
  "Bigsby",
  "Boucher",
  "Budda",
  "Bundy",
  "CAPI",
  "Chromaharp",
  "Conrad",
  "Dean Markley",
  "Diamond",
  "Diezel",
  "Doug Fleenor Design",
  "Driftwood",
  "Dunable",
  "ENGL Amplifiers",
  "ESE",
  "Floyd Rose",
  "Fostex",
  "GFS",
  "Gator Cases",
  "Gibson Custom Shop",
  "ISP Technologies",
  "JAH Audio",
  "James Tyler",
  "Jay Turser",
  "Kalamazoo",
  "Klipsch",
  "Knaggs",
  "LAG",
  "Lauten Audio",
  "Lehle",
  "Listen Technologies",
  "Livewire",
  "Luna",
  "MEINL",
  "Matchless",
  "Michael Tuttle",
  "Mullard",
  "Musser",
  "Mythos",
  "Neural DSP",
  "Neutrik",
  "Norma",
  "Otto Link",
  "Phenyx Pro",
  "Proline",
  "Quilter Labs",
  "RF Venue",
  "ROLI",
  "Rivera",
  "Rockaway Relic",
  "Solano Speed Shop",
  "Solar",
  "Stevens",
  "Telecast Fiber Systems",
  "Teye",
  "Tom Anderson",
  "Tom Anderson Guitarworks",
  "Tone King",
  "Visual Sound",
  "VocalboothtoGo",
  "Xotic",
  "bc rich",
  "AB International",
  "AJA",
  "APC",
  "ARRI",
  "Agile",
  "Altec Lansing",
  "Astatic",
  "Auralex",
  "Brian Moore Guitars",
  "C.G. Conn",
  "CTS",
  "Canare",
  "Cannonball",
  "Carlsbro",
  "Chauvet Pro",
  "Countryman",
  "DJI",
  "DR Strings",
  "DeltaLab",
  "Dingwall Guitars",
  "EASTWOOD",
  "Emerson Custom",
  "Epiphone Amplifiers",
  "Fuchs",
  "Fulltone Custom Shop",
  "GLP",
  "Giannini",
  "Gibson Accessories",
  "Glarry",
  "Hart Dynamics",
  "Hercules Stands",
  "High End Systems",
  "JMAZ Lighting",
  "Jam Pedals",
  "Jordan",
  "Kamaka",
  "Kepma",
  "LR Baggs",
  "Lakland",
  "Lava Cable",
  "Lightronics",
  "Lowell",
  "M.C. Gregory",
  "MIJ",
  "Middle Atlantic",
  "One Control",
  "P. Mauriat",
  "Polyend",
  "Raytheon",
  "Realistic",
  "Red Panda",
  "Rhodes",
  "Rogers Drums",
  "Rudder",
  "STAGG",
  "Sawtooth",
  "Sovtek",
  "Spaceman",
  "Stringjoy",
  "Tagima",
  "Tannoy",
  "Teenage Engineering",
  "Telos",
  "Teton",
  "Tripp Lite",
  "Vantage",
  "Werner Guitars",
  "WesAudio",
  "Wohler Technologies",
  "Wurlitzer",
  "Xaviere",
  "b3",
  "iConnectivity",
  "markbass",
  "A Designs",
  "ASM",
  "ATI",
  "Ableton",
  "Alembic",
  "AllParts",
  "Altec",
  "Anu",
  "Aphex",
  "Audeze",
  "BSS Soundweb",
  "Baldwin",
  "BassGroover",
  "Bedell",
  "Beetronics FX",
  "Berg Larsen",
  "Biyang",
  "CBI",
  "Canon",
  "Carr",
  "Citizen",
  "Cloud Microphones",
  "Cole Clark",
  "Cordovox",
  "Cornerstone Music Gear",
  "Crazy Tube Circuits",
  "Cre8audio",
  "Custom Kraft",
  "Custom made",
  "DPA Microphones",
  "Datavideo",
  "Dave Smith Instruments",
  "Deciduous",
  "Defil",
  "Denon DJ",
  "Disaster Area Designs",
  "Dynacord",
  "Echopark",
  "Engl",
  "Episode",
  "Excelsior",
  "Fender Japan",
  "Flamma",
  "GFI",
  "Grover Jackson",
  "H. Couf",
  "HARBINGER",
  "Hal Leonard",
  "Hamilton",
  "Harry's Engineering",
  "Hedd",
  "Hipshot",
  "Horizon",
  "Horse",
  "Howard Core",
  "ISOVOX",
  "Icon",
  "JBL Bags",
  "JJ Electronic",
  "JL Cooper",
  "Jands",
  "Jasmine",
  "Jet",
  "LaChapell Audio",
  "Louder Than Liftoff",
  "Lyon by Washburn",
  "Lyons",
  "MONO",
  "Maag Audio",
  "Mad Professor",
  "Masterclock",
  "Matsumoku",
  "Modtone",
  "MojoTone",
  "Murat Diril",
  "Neve",
  "Ormsby",
  "PDP Pacific Drums & Percussion",
  "Partscaster",
  "Pig Hog",
  "Powersoft",
  "Production Intercom",
  "Pyle",
  "Ramirez",
  "RapcoHorizon",
  "Regal",
  "Rhythm Band",
  "Roksan",
  "Rowin",
  "SJC Custom Drums",
  "Seagull Guitars",
  "Shadow Hills Industries",
  "Shubb",
  "Side Show Drums",
  "Sigma",
  "Skreddy",
  "Snarling Dogs",
  "Sound Percussion Labs",
  "Spira",
  "Squier by Fender",
  "Steven Slate Audio",
  "Summit Audio",
  "TC Helicon",
  "Tanglewood",
  "Technics",
  "Tom Holmes",
  "Traveler Guitar",
  "Traynor",
  "Tributaries",
  "Trickfish",
  "Turbosound",
  "Two Rock",
  "Urei",
  "VHT",
  "WFL III Drums",
  "Wandre",
  "Warrior",
  "Wilkinson",
  "XAct Tone Solutions",
  "myMix",
  "sonicake",
  "strobel",
  "-",
  "ARP",
  "ATC",
  "Acacia Audio",
  "Ahead",
  "All-Pedal",
  "Allora",
  "Alto Professional",
  "Amazon",
  "Anthology Gear",
  "Anthony Gallo",
  "Apple",
  "Argosy",
  "Artec",
  "Artistic Products Co.",
  "Aston Microphones",
  "Atlona",
  "B&G",
  "BAM",
  "BIG EAR Pedals",
  "BLUE",
  "BOOSEY & HAWKES",
  "Bacchus",
  "Baker",
  "Bartolini",
  "Barton",
  "Belden",
  "Bell & Hern Custom",
  "Bergantino",
  "Blessing",
  "Blueridge",
  "Bolin",
  "Bowers & Wilkins",
  "BulwarkBuilt",
  "Burl Audio",
  "Chameleon Labs",
  "Chapman",
  "Chase Bliss Audio",
  "Chase Tone",
  "Colorkey",
  "Community",
  "Condor",
  "Coral",
  "Custom Build",
  "David Clark",
  "David Thomas McNaught",
  "DeMont",
  "Dead End Guitars",
  "Deadstock",
  "Devon",
  "DiGiGrid",
  "Divided by 13",
  "Dixon",
  "Dukoff",
  "Dunable Guitars",
  "ENTTEC",
  "Eden",
  "Electronic Audio Experiments",
  "Elgato",
  "Eliminator",
  "Erica Synths",
  "Esteban",
  "FMR Audio",
  "Fano",
  "Fiberplex",
  "Fodera",
  "Fojill",
  "Foxgear",
  "Foxx",
  "GFI System",
  "GLI PRO",
  "GML",
  "Gamechanger Audio",
  "Gear Exchange",
  "Genalex",
  "Genelec",
  "Gifmen",
  "Great River",
  "Greer",
  "Grote",
  "Handmade",
  "Haynes",
  "Hermida Audio",
  "Holzknecht Guitars",
  "Hudson",
  "Hufschmid",
  "Huss & Dalton",
  "Icon Pro Audio",
  "Idiotbox",
  "Istanbul Mehmet",
  "J. Rockett",
  "JK Audio",
  "JOHNSON MILLENNIUM MILLENIUM J 12 J12 MIDI MULTI",
  "Jean Baptiste",
  "Jeff's Music Gear",
  "Jet City",
  "JodyJazz",
  "Johnson",
  "Jose Ramirez",
  "Juice Goose",
  "KEN SMITH",
  "KSR",
  "Keeley Electronics",
  "Kenwood",
  "Klang",
  "Klon",
  "Knilling",
  "L-Acoustics",
  "Lab Series",
  "Land Devices",
  "Lane CBG's",
  "Lanikai",
  "Larrive",
  "Lawton",
  "Levy's",
  "Lifton",
  "Lindell Audio",
  "Live wire solutions",
  "LogicKeyboard",
  "Logitech",
  "Loop Master Pedals",
  "Loop-Master",
  "Lounsberry Pedals",
  "Luna Guitars",
  "M-VAVE",
  "MIDI Solutions",
  "Make Noise",
  "Mayones",
  "Meyer",
  "Miktek",
  "Ming Soldering",
  "Miura",
  "Moen",
  "Monster Prolink",
  "Motion Sound",
  "Nash",
  "Netgear",
  "No Name",
  "Nobels",
  "Nordstrand Audio",
  "Oktava",
  "Old Blood Noise Endeavors",
  "Omnifex",
  "Orangewood",
  "PMC",
  "Panasonic",
  "Pascarella Guitars",
  "Paul Reed Smith",
  "Peavy",
  "Peluso",
  "Phil Jones Bass",
  "Philips Color Kinetics",
  "Phoenix Audio",
  "Pignose Amps",
  "Playwell",
  "Polytone",
  "Power Play",
  "Prescription Electronics",
  "Primacoustic",
  "Pulse percussion",
  "Que Audio",
  "RAMSA",
  "RJM Music",
  "Red Rhodes",
  "Red Witch",
  "Rivolta",
  "Roc-N-Soc",
  "Rose Electric Audio",
  "Ruby",
  "SR Technologies",
  "SR&D",
  "Sam Hill",
  "Sano",
  "Scatter Brained Concepts",
  "Scherl & Roth",
  "Silktone",
  "Sound Devices",
  "Sound Percussion",
  "Steinberg",
  "Strukture",
  "Subpac",
  "Sunn",
  "TL Audio",
  "TRIXON",
  "Temple Audio",
  "Tempo",
  "Truetone",
  "Tube-Tech",
  "Tune",
  "Turner",
  "Ultimate Support",
  "Un-branded",
  "Unison",
  "Unkown",
  "Utah",
  "Valco",
  "Valiant",
  "Ventura",
  "Victoria",
  "Vintech",
  "Viscount",
  "VocoPro",
  "WFL",
  "WFLIII",
  "WMD",
  "Webster Chicago",
  "Weller Guitars",
  "Weymann",
  "Wharfedale",
  "Wuhan",
  "York",
  "awdrums",
  "hand made",
  "lake",
  "rocktek",
  "sE",
];

export const CONDITIONS: readonly string[] = ["Mint", "Excellent", "Good", "Fair", "Poor"];

export const DECADES: readonly string[] = ["pre 1900s", "1900s", "1910s", "1920s", "1930s", "1940s", "1950s", "1960s", "1970s", "1980s", "1990s", "2000s", "2010s", "2020s"];
